name: CI/CD Pipeline
- name: Attest Build Provenance
  uses: actions/attest-build-provenance@v2.2.0
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run build
    - run: npm test 
